meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: hellobosh_leader_z1
    template: hellobosh
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
  - name: hellobosh_z1
    template: hellobosh
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      hellobosh:
        master: (( merge ))

networks: (( merge ))

properties: {}
